### ISSUE TITLE
Change availability to "free"

### ISSUE THREAD

**Issue by pmschauer** [chriscn/uoy-week-calendar#14]
Please change the availability for each entry from "busy" to "free". Thanks!

**Comment by chriscn** [comment]
Should have just fixed this now, would you mind checking that it has updated and you're happy with it.

**Comment by pmschauer** [comment]
Thanks for looking into this so quickly. It still shows every Monday as "busy" however.

**Comment by pmschauer** [comment]
The setting that seems to control this is:
TRANSP:TRANSPARENT
rather than 
X-MICROSOFT-CDO-BUSYSTATUS:FREE
Could you try that? Thanks!

**Comment by chriscn** [comment]
I've managed to find the documentation for the transparency; I'm using a third party library to manage creating the events. Hopefully this should now fix it.

**Comment by chriscn** [comment]
Still appearing as Busy in Google Calendar even though the transparency is set to transparent.

**Comment by chriscn** [comment]
I've raised an issue https://github.com/sebbo2002/ical-generator/issues/460 to see if they can provide some assistance.

**Comment by pmschauer** [comment]
Great - thank you for looking into this.  It's possible that removing X-MICROSOFT-CDO-BUSYSTATUS:FREE would work, as I see in a local calendar of my own that this line is not there, and the transparency works.

**Comment by chriscn** [comment]
I've got a feeling that is might be due to a caching issue. I've also updated the title to remove the year number and although GitHub has pushed out the new file, Google I think has cached it. 

How did you find this project by the way. I'd like to get it out there to the wider university community but not sure how.

**Comment by pmschauer** [comment]
Your project was recommended by IT Services, as an alternative to the calendar project that recently stopped.

**Comment by chriscn** [comment]
That is very interesting, I've not formally contacted them about it. Time to drop them an email...

**Comment by chriscn** [comment]
It is definitely a caching issue. If you try the alternative URL of `https://calendar.chrisnethercott.co.uk/calendar/undergraduate.ics` - you'll find that it works perfectly. 

Although I would prefer to use the GitHub url so that if I ever decide to not renew my domain the application will still function. 

<img width="454" alt="Screenshot 2023-02-04 at 08 45 53" src="https://user-images.githubusercontent.com/25829276/216758050-3f334a73-50b0-4a3c-a7ad-ab7c74cc8edc.png">

**Comment by pmschauer** [comment]
There are a lot of annoyed discussions about this issue with the calendar not refreshing: https://support.google.com/calendar/thread/41447964/why-does-google-calendar-cache-the-calendar-and-how-do-i-stop-it  Thanks for all your help with this!

**Comment by chriscn** [comment]
> There are a lot of annoyed discussions about this issue with the calendar not refreshing: https://support.google.com/calendar/thread/41447964/why-does-google-calendar-cache-the-calendar-and-how-do-i-stop-it Thanks for all your help with this!

Seems to be that Google has updated their internal cache. You'll notice the name of the calendar change from the year to the type.
